version: '3'
services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    networks:
      - redis-net

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    networks:
      - redis-net

  rate-limiter:
    build: .
    ports:
      - "8085:8085"
    networks:
      - redis-net
      
networks:
  redis-net:
    driver: bridge
