version: '3'
services:
  rate-limiter:
    build: .
    privileged: true
    ports:
      - "8085:8085"
    networks:
      - redis-net
    volumes:
      - $PWD/app:/go/src/github.com/shredx/golang-redis-rate-limiter/app
      - $PWD/conf:/go/src/github.com/shredx/golang-redis-rate-limiter/conf

  redis:
    container_name: redis
    hostname: redis
    image: redis
    networks:
      - redis-net
      
networks:
  redis-net:
    driver: bridge
